%RUN_ALL_FIGURES Reproduce all main-text and supporting figures.
clear; clc; close all;
codeDir = fileparts(mfilename('fullpath'));
addpath(codeDir,fullfile(codeDir,'functions'));
figDir = fullfile(codeDir,'figures');

scripts = { ...
    'Fig01_StudyArea.m', ...
    'Fig02_VerticalSalinityProfiles.m', ...
    'Fig03_ClimatologicalHSI_SIC.m', ...
    'Fig04_RiverRunoff.m', ...
    'Fig05_RunoffRelatedSalinity.m', ...
    'Fig06_DomainSensitivity.m', ...
    'Fig07_SamplingDomains.m', ...
    'Fig08_Runoff_HSI_SIC.m', ...
    'Fig09_HSI_SeaIceMetrics.m', ...
    'Fig10_AtmosphericControl.m', ...
    'Fig11_DecadalVariability.m', ...
    'Fig12_DiagnosticClassification.m', ...
    'FigS01_LaggedRunoffSalinity.m', ...
    'FigS02_AtmosphericControlExample.m', ...
    'FigS03_BinnedHSI_SIC.m'};

for i = 1:numel(scripts)
    fprintf('\n=== Running %s ===\n',scripts{i});
    run(fullfile(figDir,scripts{i}));
    drawnow;
    close all;
end
