%CHECK_REQUIRED_INPUTS Verify that all files required by the figure scripts exist.
thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(thisDir);
dataDir = fullfile(rootDir,'data');
geoDir  = fullfile(dataDir,'geospatial');

files = { ...
    fullfile(dataDir,'annual_river_shelf_metrics_1979_2024.mat'), ...
    fullfile(dataDir,'arctic_hsi_climatology_1979_2024.mat'), ...
    fullfile(dataDir,'marginal_sea_salinity_profiles_1979_2024.mat'), ...
    fullfile(dataDir,'runoff_salinity_distance_bins_1979_2024.mat'), ...
    fullfile(dataDir,'domain_sensitivity_hsi_sic_1979_2024.mat'), ...
    fullfile(dataDir,'sea_ice_monthly_1979_2024.mat'), ...
    fullfile(dataDir,'sea_ice_grid_coordinates.mat'), ...
    fullfile(dataDir,'wind_speed_JAS_1979_2024.mat'), ...
    fullfile(dataDir,'surface_air_temperature_JAS_1979_2024.mat'), ...
    fullfile(dataDir,'arctic_oscillation_monthly_1979_2024.mat'), ...
    fullfile(dataDir,'discharge_mackenzie_1972_2024.mat'), ...
    fullfile(dataDir,'discharge_yukon_1972_2024.mat'), ...
    fullfile(dataDir,'discharge_kolyma_1972_2024.mat'), ...
    fullfile(dataDir,'discharge_lena_1972_2024.mat'), ...
    fullfile(dataDir,'discharge_yenisei_1972_2024.mat'), ...
    fullfile(dataDir,'discharge_ob_1972_2024.mat'), ...
    fullfile(geoDir,'basin_mackenzie.mat'), ...
    fullfile(geoDir,'basin_yukon.mat'), ...
    fullfile(geoDir,'basin_kolyma.mat'), ...
    fullfile(geoDir,'basin_lena.mat'), ...
    fullfile(geoDir,'basin_yenisei.mat'), ...
    fullfile(geoDir,'basin_ob.mat'), ...
    fullfile(geoDir,'arctic_marginal_seas.shp')};

missing = {};
for i = 1:numel(files)
    if ~exist(files{i},'file')
        missing{end+1,1} = files{i}; %#ok<SAGROW>
    end
end

if isempty(missing)
    fprintf('All required input files are present.\n');
else
    fprintf('Missing %d required files:\n',numel(missing));
    fprintf('  %s\n',missing{:});
end
