%% Repository-relative setup
thisDir = fileparts(mfilename('fullpath'));
codeDir = fileparts(thisDir);
addpath(codeDir,fullfile(codeDir,'functions'));
cfg = project_config();
sys = river_shelf_systems();
close all;

%% ========================================================================
% Figure 6
% Sensitivity of HSI-SIC correlations to sampling radius
% and meridional domain-center offset
%
% IMPORTANT:
% This script ONLY loads previously calculated results:
%
% domain_sensitivity_hsi_sic_1979_2024.mat
%
% No ORAS5 NetCDF files are read.
% No HSI/SIC fields are recalculated.
%% ========================================================================




%% ========================================================================
% 1. PATHS
%% ========================================================================

dataDir = cfg.dataDir;


figure6File = ...
    fullfile( ...
    dataDir, ...
    'domain_sensitivity_hsi_sic_1979_2024.mat');


% Optional:
% annual_river_shelf_metrics_1979_2024.mat used for Figure 8
finalHSIFile = ...
    fullfile( ...
    dataDir, ...
    'annual_river_shelf_metrics_1979_2024.mat');


outFile = fullfile(cfg.outputDir,'Fig06_DomainSensitivity.png');


%% ========================================================================
% 2. LOAD FINAL FIGURE 6 RESULTS
%% ========================================================================

D = load(figure6File);


requiredVars = { ...
    'Rmat', ...
    'Pmat', ...
    'Nmat', ...
    'radii_km', ...
    'center_offset', ...
    'riverNames'};


for ii = 1:numel(requiredVars)

    if ~isfield(D,requiredVars{ii})

        error( ...
            'Missing variable "%s" in Figure6 mat file.', ...
            requiredVars{ii});

    end

end


Rmat = ...
    double(D.Rmat);


Pmat = ...
    double(D.Pmat);


Nmat = ...
    double(D.Nmat);


radii_km = ...
    double(D.radii_km(:)');


center_offset = ...
    double(D.center_offset(:)');


riverNames = ...
    D.riverNames;


nRadius = ...
    numel(radii_km);


nOffset = ...
    numel(center_offset);


nRiver = ...
    numel(riverNames);


assert( ...
    isequal( ...
    size(Rmat), ...
    [nRadius nOffset nRiver]), ...
    'Rmat dimensions do not match radii × offsets × systems.');


assert( ...
    isequal( ...
    size(Pmat), ...
    size(Rmat)), ...
    'Pmat and Rmat dimensions are inconsistent.');


%% ========================================================================
% 3. SYSTEM NAMES
%
% Force manuscript-style names with normal hyphen.
%% ========================================================================

riverNames = { ...
    'Mackenzie-Beaufort', ...
    'Yukon-Chukchi', ...
    'Kolyma-East Siberian', ...
    'Lena-Laptev', ...
    'Yenisei-Kara', ...
    'Ob-Kara'};


%% ========================================================================
% 4. PRINT FINAL 450-km / 0° RESULTS
%% ========================================================================

ir450 = ...
    find(radii_km == 450,1);


io0 = ...
    find(center_offset == 0,1);


if isempty(ir450) || isempty(io0)

    warning('450 km / 0° configuration not found.');

else

    R450 = ...
        squeeze( ...
        Rmat(ir450,io0,:));


    P450 = ...
        squeeze( ...
        Pmat(ir450,io0,:));


    fprintf('\n============================================================\n');
    fprintf('Figure 6: 450 km / 0° configuration\n');
    fprintf('============================================================\n');


    for ib = 1:nRiver

        fprintf( ...
            '%-24s  R = %7.3f   p = %.5f\n', ...
            riverNames{ib}, ...
            R450(ib), ...
            P450(ib));

    end

end


%% ========================================================================
% 5. OPTIONAL CHECK AGAINST FINAL FIGURE 8
%% ========================================================================

if exist(finalHSIFile,'file')

    H = load(finalHSIFile);


    if isfield(H,'R_HSI_SIC') && ...
       ~isempty(ir450) && ...
       ~isempty(io0)


        Rfig8 = ...
            double(H.R_HSI_SIC(:));


        fprintf('\n============================================================\n');
        fprintf('Comparison with final Figure 8\n');
        fprintf('============================================================\n');

        fprintf( ...
            '%-24s %10s %10s %12s\n', ...
            'System', ...
            'Figure6', ...
            'Figure8', ...
            'Difference');


        for ib = 1:nRiver

            fprintf( ...
                '%-24s %10.3f %10.3f %12.3f\n', ...
                riverNames{ib}, ...
                R450(ib), ...
                Rfig8(ib), ...
                R450(ib)-Rfig8(ib));

        end

    end

end


%% ========================================================================
% 6. FIGURE SETTINGS
%% ========================================================================

fig = figure( ...
    'Units','centimeters', ...
    'Position',[2 2 16 20], ...
    'Color','w');


%% ------------------------------------------------------------------------
% Panel positions
%% ------------------------------------------------------------------------

pos1 = [0.01 0.69 0.45 0.30];
pos2 = [0.46 0.69 0.43 0.30];

pos3 = [0.01 0.36 0.45 0.30];
pos4 = [0.46 0.36 0.43 0.30];

pos5 = [0.01 0.03 0.45 0.30];
pos6 = [0.46 0.03 0.43 0.30];


pos = [ ...
    pos1
    pos2
    pos3
    pos4
    pos5
    pos6];


cbPos = ...
    [0.91 0.03 0.022 0.96];


%% ------------------------------------------------------------------------
% Fonts
%% ------------------------------------------------------------------------

fontColorbar = 7;
fontOffset   = 7;
fontRadius   = 7;
fontTitle    = 9.5;
fontCell     = 6.5;


%% ========================================================================
% 7. RED-WHITE-BLUE COLORMAP
%% ========================================================================

nColor = ...
    256;


blue = ...
    [0.10 0.20 0.95];


white = ...
    [1 1 1];


red = ...
    [1.00 0.10 0.10];


nHalf = ...
    nColor/2;


cmapBlue = [ ...
    linspace(blue(1),white(1),nHalf)', ...
    linspace(blue(2),white(2),nHalf)', ...
    linspace(blue(3),white(3),nHalf)'];


cmapRed = [ ...
    linspace(white(1),red(1),nHalf)', ...
    linspace(white(2),red(2),nHalf)', ...
    linspace(white(3),red(3),nHalf)'];


mycmap = ...
    [cmapBlue;cmapRed];


%% ========================================================================
% 8. SECTOR GEOMETRY
%% ========================================================================

theta_centers_deg = ...
    linspace( ...
    0, ...
    90, ...
    nOffset);


th_edges = ...
    make_edges_0_90( ...
    theta_centers_deg);


r_edges = ...
    centers_to_edges( ...
    radii_km);


%% ------------------------------------------------------------------------
% Correlation color scale
%% ------------------------------------------------------------------------

clims = ...
    [-1 1];


missingColor = ...
    [0.95 0.95 0.95];


numFmt = ...
    '%.2f';


edgeLW = ...
    0.60;


%% ========================================================================
% 9. DRAW SIX PANELS
%% ========================================================================

for ib = 1:nRiver

    ax = axes( ...
        'Position', ...
        pos(ib,:));


    hold(ax,'on');

    axis(ax,'equal');

    axis(ax,'off');


    set( ...
        ax, ...
        'Clipping','off');


    %% --------------------------------------------------------
    % Draw R matrix
    %% --------------------------------------------------------

    rmax = ...
        draw_ring_sector_map_with_labels( ...
        ax, ...
        Rmat(:,:,ib), ...
        Pmat(:,:,ib), ...
        r_edges, ...
        th_edges, ...
        mycmap, ...
        clims, ...
        missingColor, ...
        numFmt, ...
        edgeLW, ...
        fontCell);


    %% --------------------------------------------------------
    % Offset labels
    %% --------------------------------------------------------

    add_offset_labels_on_arc( ...
        ax, ...
        theta_centers_deg, ...
        center_offset, ...
        rmax, ...
        fontOffset);


    %% --------------------------------------------------------
    % Radius axis
    %% --------------------------------------------------------

    add_horizontal_radius_axis( ...
        ax, ...
        radii_km, ...
        rmax, ...
        fontRadius);


    %% --------------------------------------------------------
    % Offset title
    %% --------------------------------------------------------

    text( ...
        ax, ...
        1.10*rmax, ...
        0.70*rmax, ...
        'Central offset [°]', ...
        'FontName','Times New Roman', ...
        'FontSize',7, ...
        'FontWeight','bold', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','bottom', ...
        'Color','k', ...
        'Clipping','off');


    %% --------------------------------------------------------
    % River-shelf system title
    %% --------------------------------------------------------

    text( ...
        ax, ...
        0.70*rmax, ...
        rmax, ...
        riverNames{ib}, ...
        'FontName','Times New Roman', ...
        'FontSize',fontTitle, ...
        'FontWeight','bold', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','bottom', ...
        'Color','k', ...
        'Clipping','off');


    %% --------------------------------------------------------
    % Plot limits
    %% --------------------------------------------------------

    yBand = ...
        0.11*rmax;


    xPad = ...
        0.04*rmax;


    yPad = ...
        0.05*rmax;


    xlim( ...
        ax, ...
        [-0.02*rmax, ...
         rmax+xPad]);


    ylim( ...
        ax, ...
        [-yBand, ...
         rmax+yPad]);


    %% --------------------------------------------------------
    % Bottom-row x label
    %% --------------------------------------------------------

    if ib == 5 || ib == 6

        text( ...
            ax, ...
            0.50, ...
            -0.03, ...
            'Sampling radius [km]', ...
            'Units','normalized', ...
            'FontName','Times New Roman', ...
            'FontSize',7, ...
            'FontWeight','bold', ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','top', ...
            'Color','k', ...
            'Clipping','off');

    end


    set( ...
        ax, ...
        'PositionConstraint','innerposition');


    hold(ax,'off');

end


%% ========================================================================
% 10. COLORBAR
%% ========================================================================

cbAx = axes( ...
    'Position', ...
    cbPos);


axis(cbAx,'off');


colormap(cbAx,mycmap);

caxis(cbAx,clims);


cb = ...
    colorbar(cbAx);


cb.Position = ...
    cbPos;


cb.Label.String = ...
    'R';


cb.Label.FontName = ...
    'Times New Roman';


cb.Label.FontSize = ...
    fontColorbar+3;


cb.Label.FontWeight = ...
    'bold';


cb.Label.Units = ...
    'normalized';


cb.Label.Position = ...
    [3.0 0.5 0];


cb.FontName = ...
    'Times New Roman';


cb.FontSize = ...
    fontColorbar;


cb.TickDirection = ...
    'out';


cb.RulerLocation = ...
    'right';


cb.Box = ...
    'on';


%% ========================================================================
% 11. FINAL APPEARANCE
%% ========================================================================

set( ...
    fig, ...
    'InvertHardcopy','off');


%% ========================================================================
% 12. EXPORT
%% ========================================================================

drawnow;

set(fig,'InvertHardcopy','off');

exportgraphics( ...
    gcf, ...
    fullfile(cfg.outputDir,'Fig06_DomainSensitivity.png'), ...
    'Resolution',600);



%% ========================================================================
% LOCAL FUNCTIONS
%% ========================================================================


function th_edges = make_edges_0_90(theta_centers_deg)

    c = ...
        theta_centers_deg(:)';


    n = ...
        numel(c);


    if n == 1

        th_edges = ...
            [0 90];

        return

    end


    mids = ...
        (c(1:end-1)+c(2:end))/2;


    th_edges = ...
        zeros(1,n+1);


    th_edges(1) = ...
        0;


    th_edges(2:n) = ...
        mids;


    th_edges(end) = ...
        90;

end


function rmax = draw_ring_sector_map_with_labels( ...
    ax, ...
    Z, ...
    P, ...
    r_edges, ...
    th_edges_deg, ...
    cmap, ...
    clims, ...
    missingColor, ...
    fmt, ...
    edgeLW, ...
    cellFont)

    [Nr,Nt] = ...
        size(Z);


    for i = Nr:-1:1

        r1 = ...
            r_edges(i);


        r2 = ...
            r_edges(i+1);


        for j = 1:Nt

            val = ...
                Z(i,j);


            t1 = ...
                deg2rad( ...
                th_edges_deg(j));


            t2 = ...
                deg2rad( ...
                th_edges_deg(j+1));


            nArc = ...
                32;


            tt_outer = ...
                linspace( ...
                t1,t2,nArc);


            tt_inner = ...
                linspace( ...
                t2,t1,nArc);


            x = [ ...
                r2*cos(tt_outer), ...
                r1*cos(tt_inner)];


            y = [ ...
                r2*sin(tt_outer), ...
                r1*sin(tt_inner)];


            %% --------------------------------------------------------
            % Cell color
            %% --------------------------------------------------------

            if isnan(val)

                fc = ...
                    missingColor;

            else

                fc = ...
                    value_to_rgb( ...
                    val, ...
                    cmap, ...
                    clims);

            end


            hp = patch( ...
                ax, ...
                x,y, ...
                fc, ...
                'EdgeColor','k', ...
                'LineWidth',edgeLW, ...
                'FaceAlpha',1);


            set( ...
                hp, ...
                'Clipping','off');


            %% --------------------------------------------------------
            % Cell text
            %% --------------------------------------------------------

            if isfinite(val)

                rc = ...
                    0.5*(r1+r2);


                tc = ...
                    0.5*(t1+t2);


                pval = ...
                    P(i,j);


                if isfinite(pval) && ...
                   pval < 0.05

                    txt = ...
                        sprintf( ...
                        '%.2f*', ...
                        val);

                else

                    txt = ...
                        sprintf( ...
                        fmt, ...
                        val);

                end


                text( ...
                    ax, ...
                    rc*cos(tc), ...
                    rc*sin(tc), ...
                    txt, ...
                    'FontName','Times New Roman', ...
                    'FontSize',cellFont, ...
                    'HorizontalAlignment','center', ...
                    'VerticalAlignment','middle', ...
                    'Color','k', ...
                    'Clipping','off');

            end

        end

    end


    rmax = ...
        max(r_edges);

end


function add_offset_labels_on_arc( ...
    ax, ...
    theta_centers_deg, ...
    offsets, ...
    rmax, ...
    fontSize)

    for k = 1:numel(theta_centers_deg)

        th = ...
            deg2rad( ...
            theta_centers_deg(k));


        x = ...
            1.04*rmax*cos(th);


        y = ...
            1.04*rmax*sin(th);


        text( ...
            ax, ...
            x,y, ...
            sprintf('%g',offsets(k)), ...
            'FontName','Times New Roman', ...
            'FontSize',fontSize, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'Color','k', ...
            'Clipping','off');

    end

end


function add_horizontal_radius_axis( ...
    ax, ...
    r_ticks, ...
    rmax, ...
    fontSize)

    plot( ...
        ax, ...
        [0 rmax], ...
        [0 0], ...
        'k-', ...
        'LineWidth',0.8, ...
        'Clipping','off');


    tickH = ...
        0.02*rmax;


    yText = ...
        -0.07*rmax;


    for rr = r_ticks(:)'

        plot( ...
            ax, ...
            [rr rr], ...
            [0 -tickH], ...
            'k-', ...
            'LineWidth',0.8, ...
            'Clipping','off');


        text( ...
            ax, ...
            rr, ...
            yText, ...
            sprintf('%d',rr), ...
            'FontName','Times New Roman', ...
            'FontSize',fontSize, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','top', ...
            'Color','k', ...
            'Clipping','off');

    end


    xLast = ...
        max(r_ticks);


    xOffset = ...
        0.08*rmax;


    text( ...
        ax, ...
        xLast+xOffset, ...
        yText, ...
        'km', ...
        'FontName','Times New Roman', ...
        'FontSize',fontSize, ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','top', ...
        'Color','k', ...
        'Clipping','off');

end


function rgb = value_to_rgb( ...
    v, ...
    cmap, ...
    clims)

    v = ...
        max( ...
        min(v,clims(2)), ...
        clims(1));


    t = ...
        (v-clims(1)) / ...
        (clims(2)-clims(1));


    idx = ...
        1 + ...
        t*(size(cmap,1)-1);


    i0 = ...
        floor(idx);


    i1 = ...
        min( ...
        i0+1, ...
        size(cmap,1));


    w = ...
        idx-i0;


    i0 = ...
        max( ...
        1, ...
        min(i0,size(cmap,1)));


    rgb = ...
        (1-w)*cmap(i0,:) + ...
        w*cmap(i1,:);

end


function edges = centers_to_edges(centers)

    centers = ...
        centers(:)';


    n = ...
        numel(centers);


    edges = ...
        zeros(1,n+1);


    if n == 1

        edges = ...
            [centers(1)-0.5 ...
             centers(1)+0.5];

        return

    end


    mids = ...
        (centers(1:end-1) + ...
         centers(2:end))/2;


    edges(2:n) = ...
        mids;


    edges(1) = ...
        centers(1) - ...
        (mids(1)-centers(1));


    edges(n+1) = ...
        centers(end) + ...
        (centers(end)-mids(end));

end
