%% Repository-relative setup
thisDir = fileparts(mfilename('fullpath'));
codeDir = fileparts(thisDir);
addpath(codeDir,fullfile(codeDir,'functions'));
cfg = project_config();
sys = river_shelf_systems();
close all;

%% ========================================================================
% Figure 12
% Diagnostic classification of shelf-dependent HSI-sea-ice relationships
%
% Classification based jointly on:
%   1. HSI relationships with local summer ice coverage (SIC and OWF)
%   2. Persistence after atmospheric adjustment
%   3. Temporal behavior in 10-year moving correlations
%
% Final classification:
%
% Strong:
%   Mackenzie-Beaufort
%   Kolyma-East Siberian
%   Yenisei-Kara
%
% Intermediate:
%   Lena-Laptev
%   Ob-Kara
%
% Weak or mixed:
%   Yukon-Chukchi
%% ========================================================================


%% ========================================================================
% 1. SYSTEM INFORMATION
%% ========================================================================

systemNames = { ...
    'Mackenzie-Beaufort', ...
    'Yukon-Chukchi', ...
    'Kolyma-East Siberian', ...
    'Lena-Laptev', ...
    'Yenisei-Kara', ...
    'Ob-Kara'};


% ------------------------------------------------------------------------
% IMPORTANT:
% These centers should be IDENTICAL to the final Figure 7 / Figure 6.
% ------------------------------------------------------------------------

mouth_lon = sys.mouthLon;
mouth_lat = sys.mouthLat;


radius_km = ...
    450;


Re = ...
    6371;


%% ========================================================================
% 2. FINAL CLASSIFICATION
%
% 1 = strong
% 2 = intermediate
% 3 = weak / mixed
%% ========================================================================

classID = [ ...
    1 ...   % Mackenzie-Beaufort
    3 ...   % Yukon-Chukchi
    1 ...   % Kolyma-East Siberian
    2 ...   % Lena-Laptev
    1 ...   % Yenisei-Kara
    2 ...   % Ob-Kara
    ];


%% ========================================================================
% 3. COLORS
%% ========================================================================

colStrong = ...
    [0.10 0.35 0.78];       % deep blue


colInter = ...
    [0.93 0.62 0.18];       % orange


colWeak = ...
    [0.78 0.82 0.86];       % light grey-blue


classColors = [ ...
    colStrong
    colInter
    colWeak];


% Sampling-domain fill transparency
alphaDomain = ...
    0.34;


% Domain outline
domainEdge = ...
    [0.12 0.22 0.38];


% Drainage basin boundary
colorBasin = ...
    [0.55 0.22 0.18];


% Marginal-sea boundary
edgeColor = ...
    [0.08 0.22 0.42];


coastColor = ...
    [0.40 0.40 0.40];


%% ========================================================================
% 4. FIGURE AND PROJECTION
%% ========================================================================

fig = figure( ...
    'Units','centimeters', ...
    'Position',[2 2 13.5 14.5], ...
    'Color','w');


subplot( ...
    'Position', ...
    [0.02 0.18 0.96 0.78]);


m_proj( ...
    'stereographic', ...
    'lat',90, ...
    'long',0, ...
    'radius',30);


hold on;


%% ========================================================================
% 5. BATHYMETRY
%% ========================================================================

try

    [~,hBath] = ...
        m_tbase( ...
        'contour', ...
        -6000:1000:0);


    set( ...
        hBath, ...
        'LineWidth',0.30, ...
        'LineColor',[0.82 0.86 0.90]);

catch

end


%% ========================================================================
% 6. LOAD MARGINAL SEA POLYGONS
%% ========================================================================

S = shaperead( ...
    fullfile(cfg.geoDir,'arctic_marginal_seas.shp'));


%% ========================================================================
% 7. DRAW CLASSIFIED 450-km RIVER-SHELF DOMAINS
%% ========================================================================

for ib = 1:6

    % ------------------------------------------------------------
    % Generate geodesic circle
    % ------------------------------------------------------------

    [circle_lon,circle_lat] = ...
        geodesic_circle( ...
        mouth_lon(ib), ...
        mouth_lat(ib), ...
        radius_km, ...
        Re, ...
        240);


    thisColor = ...
        classColors(classID(ib),:);


    hp = ...
        m_patch( ...
        circle_lon, ...
        circle_lat, ...
        thisColor, ...
        'EdgeColor',domainEdge, ...
        'LineWidth',1.05);


    try

        set( ...
            hp, ...
            'FaceAlpha',alphaDomain);

    catch

    end

end


%% ========================================================================
% 8. COASTLINE
%
% Draw land AFTER domains so that classification only appears over ocean.
%% ========================================================================

m_coast( ...
    'patch', ...
    [0.92 0.90 0.85], ...
    'edgecolor',coastColor, ...
    'LineWidth',0.50);


try

    m_gshhs( ...
        'fc', ...
        'color', ...
        [0.50 0.50 0.50]);

catch

end


m_grid( ...
    'box','fancy', ...
    'tickdir','in', ...
    'gridlines','no', ...
    'fontsize',8, ...
    'yticklabel',[], ...
    'xticklabel',[]);


%% ========================================================================
% 9. MARGINAL SEA BOUNDARIES
%% ========================================================================

for i = 1:length(S)

    if isfield(S(i),'X') && ...
       ~isempty(S(i).X)


        % light halo
        m_line( ...
            S(i).X, ...
            S(i).Y, ...
            'Color',[0.92 0.95 0.98], ...
            'LineWidth',2.2);


        % main boundary
        m_line( ...
            S(i).X, ...
            S(i).Y, ...
            'Color',edgeColor, ...
            'LineWidth',1.0);

    end

end


%% ========================================================================
% 10. RIVER BASIN OUTLINES
%% ========================================================================

basinFiles = { ...
    'basin_mackenzie.mat', ...
    'basin_yukon.mat', ...
    'basin_kolyma.mat', ...
    'basin_lena.mat', ...
    'basin_yenisei.mat', ...
    'basin_ob.mat'};

for ib = 1:numel(basinFiles)
    B = load_basin_boundary(fullfile(cfg.geoDir,basinFiles{ib}));
    m_plot(B(1,:),B(2,:),'color',colorBasin,'LineWidth',0.70);
end


%% ========================================================================
% 11. SEA LABELS
%% ========================================================================

sea_lon = [ ...
    -169, ...
    -138.65, ...
     165.76, ...
      80.08, ...
     121.39];


sea_lat = [ ...
    70, ...
    75.00, ...
    75.81, ...
    79.38, ...
    76.74];


sea_name = { ...
    'Chukchi Sea', ...
    'Beaufort Sea', ...
    'East Siberian Sea', ...
    'Kara Sea', ...
    'Laptev Sea'};


for i = 1:length(sea_name)

    m_text( ...
        sea_lon(i), ...
        sea_lat(i), ...
        sea_name{i}, ...
        'FontSize',6.5, ...
        'FontName','Times New Roman', ...
        'FontWeight','bold', ...
        'FontAngle','italic', ...
        'Color',[0.45 0.12 0.12], ...
        'HorizontalAlignment','center');

end


%% ========================================================================
% 12. RIVER-SHELF SYSTEM BADGES
%% ========================================================================

badgeSize = ...
    9;


badgeBlue = ...
    [50 90 160]/255;


badgeEdge = ...
    [30 60 110]/255;


numFont = ...
    8;


% Keep your previous badge positions
pos = [ ...
    -120.5 60.8
    -147.5 66.2
     157.0 65.5
     124.0 63.0
      94.0 61.0
      76.0 62.0];


labels = ...
    {'1','2','3','4','5','6'};


for k = 1:6

    m_line( ...
        pos(k,1), ...
        pos(k,2), ...
        'marker','o', ...
        'markersize',badgeSize, ...
        'MarkerFaceColor',badgeBlue, ...
        'color',badgeEdge, ...
        'LineWidth',0.80);


    m_text( ...
        pos(k,1), ...
        pos(k,2), ...
        labels{k}, ...
        'color','w', ...
        'FontSize',numFont, ...
        'FontWeight','bold', ...
        'FontName','Times New Roman', ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle');

end


%% ========================================================================
% 13. OPTIONAL COLORED SYSTEM MARKERS AT RIVER MOUTHS
%
% These make the classification unambiguous even where circles overlap,
% especially Yenisei-Kara and Ob-Kara.
%% ========================================================================

for ib = 1:6

    cc = ...
        classColors(classID(ib),:);


    m_line( ...
        mouth_lon(ib), ...
        mouth_lat(ib), ...
        'Marker','o', ...
        'MarkerSize',5.5, ...
        'MarkerFaceColor',cc, ...
        'MarkerEdgeColor','k', ...
        'LineWidth',0.6);

end


%% ========================================================================
% 14. LEGEND
%% ========================================================================

hStrong = ...
    patch( ...
    nan,nan, ...
    colStrong, ...
    'FaceAlpha',alphaDomain, ...
    'EdgeColor',domainEdge, ...
    'LineWidth',0.8);


hInter = ...
    patch( ...
    nan,nan, ...
    colInter, ...
    'FaceAlpha',alphaDomain, ...
    'EdgeColor',domainEdge, ...
    'LineWidth',0.8);


hWeak = ...
    patch( ...
    nan,nan, ...
    colWeak, ...
    'FaceAlpha',alphaDomain, ...
    'EdgeColor',domainEdge, ...
    'LineWidth',0.8);


lgd = legend( ...
    [hStrong hInter hWeak], ...
    { ...
    'Strong HSI-sea-ice association', ...
    'Intermediate association', ...
    'Weak or mixed association'}, ...
    'Location','none', ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontName','Times New Roman', ...
    'FontSize',7.5, ...
    'FontWeight','bold');


lgd.Units = ...
    'normalized';


lgd.Position = ...
    [0.08 0.095 0.86 0.075];


lgd.ItemTokenSize = ...
    [12 12];


%% ========================================================================
% 15. EXPORT
%% ========================================================================

set( ...
    fig, ...
    'InvertHardcopy','off');


exportgraphics( ...
    fig, ...
    fullfile(cfg.outputDir,'Fig12_DiagnosticClassification.png'), ...
    'Resolution',600);



%% ========================================================================
% LOCAL FUNCTION
%% ========================================================================

function [lonCircle,latCircle] = ...
    geodesic_circle( ...
    lon0, ...
    lat0, ...
    radius_km, ...
    Re, ...
    nPoint)

% Great-circle circle around lon0/lat0

    bearing = ...
        linspace( ...
        0, ...
        2*pi, ...
        nPoint);


    delta = ...
        radius_km/Re;


    lat0r = ...
        deg2rad(lat0);


    lon0r = ...
        deg2rad(lon0);


    latr = ...
        asin( ...
        sin(lat0r).*cos(delta) + ...
        cos(lat0r).*sin(delta).*cos(bearing));


    lonr = ...
        lon0r + ...
        atan2( ...
        sin(bearing).*sin(delta).*cos(lat0r), ...
        cos(delta)-sin(lat0r).*sin(latr));


    latCircle = ...
        rad2deg(latr);


    lonCircle = ...
        rad2deg(lonr);


    lonCircle = ...
        mod(lonCircle+180,360)-180;

end
