%% Repository-relative setup
thisDir = fileparts(mfilename('fullpath'));
codeDir = fileparts(thisDir);
addpath(codeDir,fullfile(codeDir,'functions'));
cfg = project_config();
sys = river_shelf_systems();
close all;

%% ========================================================================
% Figure 11
% Decadal variability of HSI-SIC relationships
%
% (a) 10-year moving correlations for six river-shelf systems
%     and regional mean
%
% (b) Distribution of regional-mean moving correlations
%     for four descriptive periods
%
% Period: 1979-2024
%
% IMPORTANT:
%   - Uses FINAL HSI_JAS_dt and SIC_JAS_dt directly from annual_river_shelf_metrics_1979_2024.mat
%   - No repeated detrending
%   - No old hard-coded results
%% ========================================================================




%% ========================================================================
% 1. LOAD FINAL DATA
%% ========================================================================

dataFile = fullfile(cfg.dataDir,'annual_river_shelf_metrics_1979_2024.mat');

D = load(dataFile);


%% ------------------------------------------------------------------------
% Required variables
%% ------------------------------------------------------------------------

if ~isfield(D,'HSI_JAS_dt')
    error('Annual metrics file does not contain HSI_JAS_dt.');
end

if ~isfield(D,'SIC_JAS_dt')
    error('Annual metrics file does not contain SIC_JAS_dt.');
end

if ~isfield(D,'years')
    error('Annual metrics file does not contain years.');
end


HSI_dt = ...
    double(D.HSI_JAS_dt);

SIC_dt = ...
    double(D.SIC_JAS_dt);

years = ...
    double(D.years(:));


%% ------------------------------------------------------------------------
% Convert orientation to 46 × 6
%% ------------------------------------------------------------------------

if size(HSI_dt,1) == 6 && ...
   size(HSI_dt,2) == 46

    HSI_dt = HSI_dt';

end


if size(SIC_dt,1) == 6 && ...
   size(SIC_dt,2) == 46

    SIC_dt = SIC_dt';

end


assert( ...
    isequal(size(HSI_dt),[46 6]), ...
    'HSI_JAS_dt must be 46 × 6.');


assert( ...
    isequal(size(SIC_dt),[46 6]), ...
    'SIC_JAS_dt must be 46 × 6.');


assert( ...
    numel(years) == 46, ...
    'years must contain 1979-2024.');


nYear = ...
    numel(years);

nBasin = ...
    6;


%% ========================================================================
% 2. SYSTEM NAMES
%% ========================================================================

basinNames = { ...
    'Mackenzie-Beaufort', ...
    'Yukon-Chukchi', ...
    'Kolyma-East Siberian', ...
    'Lena-Laptev', ...
    'Yenisei-Kara', ...
    'Ob-Kara'};


shortNames = { ...
    'Mackenzie', ...
    'Yukon', ...
    'Kolyma', ...
    'Lena', ...
    'Yenisei', ...
    'Ob'};


%% ========================================================================
% 3. 10-YEAR MOVING CORRELATIONS
%% ========================================================================

win = ...
    10;


nRun = ...
    nYear-win+1;


R = ...
    nan(nBasin,nRun);


P = ...
    nan(nBasin,nRun);


N = ...
    nan(nBasin,nRun);


yr_mid = ...
    nan(1,nRun);


%% ------------------------------------------------------------------------
% Window-center year
%
% For a 10-year window:
% 1979-1988 -> 1983.5
% ...
% 2015-2024 -> 2019.5
%% ------------------------------------------------------------------------

for iw = 1:nRun

    yr_mid(iw) = ...
        mean( ...
        years(iw:iw+win-1));

end


%% ------------------------------------------------------------------------
% Moving Pearson correlations
%% ------------------------------------------------------------------------

for ib = 1:nBasin

    x = ...
        HSI_dt(:,ib);

    y = ...
        SIC_dt(:,ib);


    for iw = 1:nRun

        xx = ...
            x(iw:iw+win-1);

        yy = ...
            y(iw:iw+win-1);


        valid = ...
            isfinite(xx) & ...
            isfinite(yy);


        N(ib,iw) = ...
            nnz(valid);


        if N(ib,iw) >= 5 && ...
           std(xx(valid)) > 0 && ...
           std(yy(valid)) > 0

            [R(ib,iw),P(ib,iw)] = ...
                corr( ...
                xx(valid), ...
                yy(valid), ...
                'Rows','complete');

        end

    end

end


%% ========================================================================
% 4. REGIONAL MEAN
%
% Keep arithmetic mean for consistency with manuscript definition.
%% ========================================================================

Rmean = ...
    mean( ...
    R, ...
    1, ...
    'omitnan');


%% ========================================================================
% 5. DESCRIPTIVE PERIODS
%
% Grouping is based on WINDOW-CENTER YEAR.
%% ========================================================================

periodGroup = ...
    nan(size(yr_mid));


periodGroup( ...
    yr_mid < 1990) = ...
    1;


periodGroup( ...
    yr_mid >= 1990 & ...
    yr_mid < 2000) = ...
    2;


periodGroup( ...
    yr_mid >= 2000 & ...
    yr_mid < 2010) = ...
    3;


periodGroup( ...
    yr_mid >= 2010) = ...
    4;


periodLabels = { ...
    '1979-1989', ...
    '1990-1999', ...
    '2000-2009', ...
    '2010-2024'};


%% ------------------------------------------------------------------------
% Period statistics
%% ------------------------------------------------------------------------

periodMean = ...
    nan(1,4);


periodMedian = ...
    nan(1,4);


periodN = ...
    nan(1,4);


for ip = 1:4

    tmp = ...
        Rmean(periodGroup == ip);


    tmp = ...
        tmp(isfinite(tmp));


    periodN(ip) = ...
        numel(tmp);


    if ~isempty(tmp)

        periodMean(ip) = ...
            mean(tmp);

        periodMedian(ip) = ...
            median(tmp);

    end

end


%% ========================================================================
% 6. DISPLAY RESULTS
%% ========================================================================

fprintf('\n============================================================\n');
fprintf('FIGURE 11: DECADAL HSI-SIC CORRELATION\n');
fprintf('============================================================\n');


fprintf('\nPeriod means based on window-center years:\n\n');


for ip = 1:4

    fprintf( ...
        '%-12s  mean = %.3f   median = %.3f   N = %d\n', ...
        periodLabels{ip}, ...
        periodMean(ip), ...
        periodMedian(ip), ...
        periodN(ip));

end


fprintf('\nFull moving-correlation range:\n');

fprintf( ...
    'Regional mean: %.3f to %.3f\n', ...
    min(Rmean,[],'omitnan'), ...
    max(Rmean,[],'omitnan'));


%% ========================================================================
% 7. SAVE INTERMEDIATE RESULTS
%% ========================================================================

outDir = cfg.outputDir;


if ~exist(outDir,'dir')
    mkdir(outDir);
end


save( ...
    fullfile( ...
    outDir, ...
    'Figure11_HSI_SIC_decadal_results.mat'), ...
    ...
    'R', ...
    'P', ...
    'N', ...
    'Rmean', ...
    'yr_mid', ...
    'periodGroup', ...
    'periodLabels', ...
    'periodMean', ...
    'periodMedian', ...
    'periodN', ...
    'years', ...
    'basinNames', ...
    'shortNames', ...
    'win');


%% ========================================================================
% 8. FIGURE SETTINGS
%% ========================================================================

fig = figure( ...
    'Units','centimeters', ...
    'Position',[2 2 18.5 9.2], ...
    'Color','w');


tl = tiledlayout( ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


fontAxis   = 7.5;
fontLabel  = 8.5;
fontLegend = 6.3;
fontPanel  = 10;


cols = ...
    lines(6);


%% ========================================================================
% 9. PANEL (a): 10-YEAR MOVING CORRELATIONS
%% ========================================================================

ax1 = ...
    nexttile(tl,1);


hold(ax1,'on');


yl = ...
    [-1 1];


%% ------------------------------------------------------------------------
% Light period background
%% ------------------------------------------------------------------------

patch( ...
    ax1, ...
    [min(yr_mid) 1990 1990 min(yr_mid)], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    [0.92 0.92 0.92], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.18);


patch( ...
    ax1, ...
    [1990 2000 2000 1990], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    [0.88 0.88 0.88], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.15);


patch( ...
    ax1, ...
    [2000 2010 2010 2000], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    [0.84 0.84 0.84], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.12);


patch( ...
    ax1, ...
    [2010 max(yr_mid) max(yr_mid) 2010], ...
    [yl(1) yl(1) yl(2) yl(2)], ...
    [0.80 0.80 0.80], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.10);


%% ------------------------------------------------------------------------
% Individual systems
%% ------------------------------------------------------------------------

h = ...
    gobjects(nBasin,1);


for ib = 1:nBasin

    h(ib) = ...
        plot( ...
        ax1, ...
        yr_mid, ...
        R(ib,:), ...
        '-', ...
        'Color',cols(ib,:), ...
        'LineWidth',0.95, ...
        'DisplayName',shortNames{ib});

end


%% ------------------------------------------------------------------------
% Regional mean
%% ------------------------------------------------------------------------

hMean = ...
    plot( ...
    ax1, ...
    yr_mid, ...
    Rmean, ...
    '-', ...
    'Color',[0 0 0], ...
    'LineWidth',2.20, ...
    'DisplayName','Regional mean');


%% ------------------------------------------------------------------------
% Period boundaries
%% ------------------------------------------------------------------------

xline( ...
    ax1, ...
    1990, ...
    '--', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',0.8);


xline( ...
    ax1, ...
    2000, ...
    '--', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',0.8);


xline( ...
    ax1, ...
    2010, ...
    '--', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',0.8);


%% ------------------------------------------------------------------------
% Zero line
%% ------------------------------------------------------------------------

yline( ...
    ax1, ...
    0, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.8);


%% ------------------------------------------------------------------------
% Axes
%% ------------------------------------------------------------------------

xlim( ...
    ax1, ...
    [floor(min(yr_mid)) ...
     ceil(max(yr_mid))]);


ylim( ...
    ax1, ...
    yl);


xticks( ...
    ax1, ...
    1985:5:2020);


yticks( ...
    ax1, ...
    -1:0.2:1);


xlabel( ...
    ax1, ...
    'Window center year', ...
    'FontName','Times New Roman', ...
    'FontSize',fontLabel, ...
    'FontWeight','bold');


ylabel( ...
    ax1, ...
    '10-year running correlation', ...
    'FontName','Times New Roman', ...
    'FontSize',fontLabel, ...
    'FontWeight','bold');


grid(ax1,'on');


ax1.GridColor = ...
    [0.75 0.75 0.75];


ax1.GridAlpha = ...
    0.28;


set( ...
    ax1, ...
    'FontName','Times New Roman', ...
    'FontSize',fontAxis, ...
    'FontWeight','bold', ...
    'LineWidth',0.8, ...
    'TickDir','out', ...
    'Box','off', ...
    'Layer','top');


%% ------------------------------------------------------------------------
% Legend
%% ------------------------------------------------------------------------

lgd = ...
    legend( ...
    ax1, ...
    [h;hMean], ...
    'Location','southoutside', ...
    'Box','off', ...
    'Orientation','horizontal', ...
    'FontName','Times New Roman', ...
    'FontSize',fontLegend, ...
    'FontWeight','bold', ...
    'NumColumns',4);


lgd.ItemTokenSize = ...
    [8 4];


%% ------------------------------------------------------------------------
% Panel label
%% ------------------------------------------------------------------------

text( ...
    ax1, ...
    0.03, ...
    0.95, ...
    '(a)', ...
    'Units','normalized', ...
    'FontName','Times New Roman', ...
    'FontSize',fontPanel, ...
    'FontWeight','bold', ...
    'VerticalAlignment','top');


%% ========================================================================
% 10. PANEL (b): PERIOD DISTRIBUTIONS
%% ========================================================================

ax2 = ...
    nexttile(tl,2);


hold(ax2,'on');


valid = ...
    isfinite(Rmean) & ...
    isfinite(periodGroup);


R_box = ...
    Rmean(valid)';


G_box = ...
    periodGroup(valid)';


%% ------------------------------------------------------------------------
% Boxplot
%% ------------------------------------------------------------------------

boxplot( ...
    ax2, ...
    R_box, ...
    G_box, ...
    'Labels',periodLabels, ...
    'Symbol','', ...
    'Whisker',1.5, ...
    'Widths',0.55, ...
    'Colors',[0 0 0]);


%% ------------------------------------------------------------------------
% Box colors
%% ------------------------------------------------------------------------

hBox = ...
    findobj( ...
    ax2, ...
    'Tag','Box');


boxColors = [ ...
    0.80 0.88 0.95
    0.64 0.80 0.92
    0.46 0.68 0.86
    0.26 0.52 0.78];


for j = 1:length(hBox)

    patch( ...
        ax2, ...
        get(hBox(j),'XData'), ...
        get(hBox(j),'YData'), ...
        boxColors(length(hBox)-j+1,:), ...
        'FaceAlpha',0.72, ...
        'EdgeColor','k');

end


%% ------------------------------------------------------------------------
% Median lines
%% ------------------------------------------------------------------------

hMed = ...
    findobj( ...
    ax2, ...
    'Tag','Median');


for j = 1:length(hMed)

    set( ...
        hMed(j), ...
        'LineWidth',1.25, ...
        'Color','k');

end


%% ------------------------------------------------------------------------
% Period mean points
%% ------------------------------------------------------------------------

for ip = 1:4

    yy = ...
        Rmean( ...
        periodGroup == ip);


    yy = ...
        yy(isfinite(yy));


    if ~isempty(yy)

        plot( ...
            ax2, ...
            ip, ...
            mean(yy), ...
            'ko', ...
            'MarkerFaceColor','k', ...
            'MarkerSize',4.0);

    end

end


%% ------------------------------------------------------------------------
% Zero line
%% ------------------------------------------------------------------------

yline( ...
    ax2, ...
    0, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.8);


%% ------------------------------------------------------------------------
% Y-axis range
%
% Automatically adjust based on current final data.
%% ------------------------------------------------------------------------

ymin = ...
    min(Rmean,[],'omitnan');


ymax = ...
    max(Rmean,[],'omitnan');


yLow = ...
    min(0, ...
    floor((ymin-0.05)*10)/10);


yHigh = ...
    max(0.6, ...
    ceil((ymax+0.05)*10)/10);


ylim( ...
    ax2, ...
    [0.3 yHigh]);


ylabel( ...
    ax2, ...
    'Regional mean R(HSI, SIC)', ...
    'FontName','Times New Roman', ...
    'FontSize',fontLabel, ...
    'FontWeight','bold');


grid(ax2,'on');


ax2.GridColor = ...
    [0.75 0.75 0.75];


ax2.GridAlpha = ...
    0.28;


set( ...
    ax2, ...
    'FontName','Times New Roman', ...
    'FontSize',fontAxis, ...
    'FontWeight','bold', ...
    'LineWidth',0.8, ...
    'TickDir','out', ...
    'Box','off', ...
    'Layer','top');


%% ------------------------------------------------------------------------
% Panel label
%% ------------------------------------------------------------------------

text( ...
    ax2, ...
    0.03, ...
    0.95, ...
    '(b)', ...
    'Units','normalized', ...
    'FontName','Times New Roman', ...
    'FontSize',fontPanel, ...
    'FontWeight','bold', ...
    'VerticalAlignment','top');


%% ========================================================================
% 11. EXPORT
%% ========================================================================

drawnow;

set(fig,'InvertHardcopy','off');

exportgraphics( ...
    gcf, ...
    fullfile(cfg.outputDir,'Fig11_DecadalVariability.png'), ...
    'Resolution',600);
